#!/bin/bash
 
################################################################################
#
# Copyright (c) 2008-2009 Christopher J. Stawarz
#
# Modified by Nathaniel Gray in 2012 to support Clang, custom dev tool locations, 
# and armv7.  Also removed "make install" phase, since that can easily be done by
# hand.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################
 
 
 
# Disallow undefined variables
set -u
 

default_ndk="/Users/bquenin/android-ndk-r8d"
default_toolchain="/Users/bquenin/android-toolchain"
 
export NDK_DIR="${NDK_DIR:-$default_ndk}"
export TOOLCHAIN_DIR="${TOOLCHAIN_DIR:-$default_toolchain}"

usage ()
{
    cat >&2 << EOF
Usage: ${0##*/} [-ht] [-p prefix] target [configure_args]
       -h	Print help message
       -p	Installation prefix (default: \$HOME/Developer/Platforms/...)

The target must be "arm".
Any additional arguments are passed to configure.
 
The following environment variables affect the build process:
 
 NDK_DIR                    (default: $default_ndk)
 TOOLCHAIN_DIR              (default: $default_toolchain)
 
EOF
}
 
while getopts ":hp:t" opt; do
    case $opt in
    h  ) usage ; exit 0 ;;
    p  ) prefix="$OPTARG" ;;
    \? ) usage ; exit 2 ;;
    esac
done
shift $(( $OPTIND - 1 ))
 
if (( $# < 1 )); then
    usage
    exit 2
fi
 
target=$1
shift
 
case $target in
 
    arm )
    arch=arm-eabi
    extra_cflags=""
    ;;
    
    * )
    usage
    exit 2
 
esac
 
 
platform_dir="$TOOLCHAIN_DIR"
platform_bin_dir="${platform_dir}/bin"

#
# Define Tools
#
CC=arm-linux-androideabi-gcc
CXX=arm-linux-androideabi-g++
LINK=${CXX}
STRIP=arm-linux-androideabi-strip
LIB="arm-linux-androideabi-ar -cr"
RANLIB=arm-linux-androideabi-ranlib

export CC="${platform_bin_dir}/${CC}"
export CXX="${platform_bin_dir}/${CXX}"
export CPP="${CC} -E"
export CXXCPP="${CPP}"
export LINK="${CXX}"
export STRIP="${platform_bin_dir}/arm-linux-androideabi-strip"
export LIB="${platform_bin_dir}/arm-linux-androideabi-ar -cr"
export RANLIB="${platform_bin_dir}/arm-linux-androideabi-ranlib"

#
# Compiler and Linker Flags
#
export CFLAGS="-isysroot ${platform_dir}/sysroot ${extra_cflags}"
export CXXFLAGS="-isysroot ${platform_dir}/sysroot ${extra_cflags}"
export LDFLAGS="-isysroot ${platform_dir}/sysroot"

./configure \
    --host="${arch}" \
    --disable-shared \
    --enable-static \
    "$@" || exit
 
cat >&2 << EOF
 
Configure succeeded!
 
EOF
